import requests
import os

def get_access_token(client_id, client_secret, refresh_token):
    token_url = "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
    data = {
        "client_id": client_id,
        "client_secret": client_secret,
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
        "scope": "offline_access Files.ReadWrite"
    }
    response = requests.post(token_url, data=data)
    response.raise_for_status()
    token_data = response.json()
    return token_data["access_token"]

def upload_to_onedrive(access_token, file_path, drive_path):
    """
    Uploads (or replaces) a file to OneDrive.
    Example drive_path: 'Reports/server1_records.csv'
    """
    upload_url = f"https://graph.microsoft.com/v1.0/me/drive/root:/{drive_path}:/content"
    headers = {"Authorization": f"Bearer {access_token}"}

    with open(file_path, "rb") as f:
        response = requests.put(upload_url, headers=headers, data=f)
    response.raise_for_status()

    uploaded_info = response.json()
    print(f"✅ File '{uploaded_info['name']}' uploaded successfully at {uploaded_info['lastModifiedDateTime']}")

if __name__ == "__main__":
    CLIENT_ID = os.environ["CLIENT_ID"]
    CLIENT_SECRET = os.environ["CLIENT_SECRET"]
    REFRESH_TOKEN = os.environ["REFRESH_TOKEN"]

    # Get a new access token
    access_token = get_access_token(CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN)

    # Path to local CSV generated by your script
    local_file = "/home/runner/work/PowerBIauto/PowerBIauto/downloads/final_report.csv"

    # Path in OneDrive (modify as needed)
    onedrive_path = "Reports/final_report.csv"
    
    if os.path.exists(local_file):
        upload_to_onedrive(access_token, local_file, onedrive_path)
