name: Upload CSV to OneDrive

on:
  schedule:
    - cron: "*/20 * * * *"   # runs every 20 minutes
  workflow_dispatch:          # allows manual run

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Run scraper
      run: |
      python -u main.py > runlog.txt 2>&1 || true
      echo "---- START LOG ----"
      cat runlog.txt
      echo "---- END LOG ----"

    - name: Upload full log
        uses: actions/upload-artifact@v4
        with:
          name: debug-log
          path: runlog.txt

    - name: Upload to OneDrive
      env:
        CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.ONEDRIVE_REFRESH_TOKEN }}
      run: |
        python upload_to_onedrive.py
