name: Update Power BI Data

on:
  schedule:
    - cron: "*/20 * * * *"   # every 20 minutes
  workflow_dispatch:          # allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run script
        run: python main.py

      - name: Upload to OneDrive
        uses: skitionek/onedrive-upload@v2.3.0
        with:
          source: ./merged_report.csv
          target: /PowerBI_Data/merged_report.csv
        env:
          ONEDRIVE_REFRESH_TOKEN: ${{ secrets.ONEDRIVE_REFRESH_TOKEN }}
